version: "3.9"
services:
  traefik:
    image: traefik:2.6
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - /var/lib/traefik/letsencrypt:/letsencrypt
      - /var/logs:/var/logs
    environment:
      - DOMAIN=localhost
    networks:
      - traefik

  backend:
    hostname: backend
    stdin_open: true
    tty: true
    build: ../backend
    restart: always
    volumes:
      - ../backend:/wtw
    networks:
      - internal
      - traefik

  frontend:
    hostname: webfrontend
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    tty: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/wtw
      - /wtw/node_modules
    healthcheck:
      disable: true
    networks:
      - internal
      - traefik

  arangodb:
    hostname: arangodb
    build: arangodb
    env_file: .env
    restart: always
    depends_on:
      - traefik
    volumes:
      - /var/lib/arangodb3:/var/lib/arangodb3
    networks:
      - internal
      - traefik

networks:
  traefik:
    driver: bridge
  internal:
    driver: bridge
