version: "3.9"
services:
  traefik:
    image: traefik:2.6
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - /var/lib/traefik/letsencrypt:/letsencrypt
      - /var/logs:/var/logs
    environment:
      - DOMAIN=localhost
    networks:
      - traefik

  strapi:
    hostname: strapi
    build: strapi
    env_file: .env
    restart: always
    depends_on:
      - traefik
    volumes:
      - ./strapi/veedelsretter:/opt/app
      - /opt/app/node_modules
    networks:
      - internal
      - traefik

  backend:
    hostname: backend
    stdin_open: true
    tty: true
    build: ../backend
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ../backend:/wtw
    networks:
      - internal
      - traefik

  frontend:
    hostname: webfrontend
    build:
      context: ../frontend
      dockerfile: dev.Dockerfile
    tty: true
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/wtw
      - /wtw/node_modules
    healthcheck:
      disable: true
    networks:
      - internal
      - traefik

networks:
  traefik:
    driver: bridge
  internal:
    driver: bridge
