version: "3.4"
services:
  traefik:
    image: traefik:2.6
    restart: unless-stopped
    ports:
      - "1030:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - /var/lib/traefik/letsencrypt:/letsencrypt
      - /var/logs:/var/logs
    environment:
      - DOMAIN=web102.in-p.de
    networks:
      - traefik

  backend:
    hostname: backend
    stdin_open: true
    tty: true
    build: ../backend
    restart: always
    env_file: /home/wtw/.env
    volumes:
      - ../backend:/wtw
    networks:
      - internal
      - traefik

  frontend:
    hostname: webfrontend
    build:
      context: ../frontend
      dockerfile: production.Dockerfile
    tty: true
    restart: always
    volumes:
      - /wtw/node_modules
    healthcheck:
      disable: true
    networks:
      - internal
      - traefik

  strapi:
    hostname: strapi
    build: strapi
    env_file: .env
    restart: always
    depends_on:
      - traefik
    volumes:
      - strapi/veedelsretter/config:/opt/app/config
      - strapi/veedelsretter/src:/opt/app/src
      - strapi/veedelsretter/package.json:/opt/package.json
      - strapi/veedelsretter/yarn.lock:/opt/yarn.lock
      - strapi/veedelsretter/.env:/opt/app/.env
    networks:
      - internal
      - traefik

networks:
  traefik:
    driver: bridge
  internal:
    driver: bridge
