http:
  routers:
    dashboard:
      entryPoints: ["web", "websecure"]
      middlewares: ["redirectHTTPS"]
      service: api@internal
      rule: Host(`dashboard.{{env "DOMAIN"}}`)
      tls:
        certResolver: letsencrypt

    strapi:
      entryPoints: ["web"]
      middlewares: []
      service: strapi-service
      rule: Host(`strapi.{{ env "DOMAIN" }}`)
      tls:
        certResolver: letsencrypt

    frontend:
      entryPoints: ["web"]
      middlewares: []
      service: frontend-service
      rule: Host(`{{ env "DOMAIN" }}`)

    backend:
      entryPoints: ["web"]
      middlewares: []
      service: backend-service
      rule: Host(`backend.{{ env "DOMAIN" }}`)
