http:
  services:
    frontend-service:
      loadBalancer:
        servers:
          - url: http://webfrontend:3000

    backend-service:
      loadBalancer:
        servers:
          - url: http://backend:5000
