defaultEntryPoints: ["websecure"]

log:
  level: DEBUG
  filePath: /var/logs/traefik.log

accessLog:
  filePath: /var/logs/access.log
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-449"
      - "500-511"

providers:
  file:
    directory: /etc/traefik
    watch: true

api:
  dashboard: true
  insecure: false
  debug: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencrypt:
    acme:
      email: info@ads-medienmanufaktur.de
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
