name: Deploy Release
on:
  push:
    branches:
      - 'automatic-release-tag'
jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

  frontend:
    runs-on: self-hosted
    steps:
      - name: Build Frontend
        run: |
          cd frontend
          npm i --unsafe-perm -g npm@latest expo-cli@latest
          npm ci
          npm run build
          cd ../docker
          docker-compose up -d --build frontend

  backend:
    runs-on: self-hosted
    steps:
      - name: Build Backend
        run: |
          cd docker
          docker-compose up -d --build backend

  start-containers:
    runs-on: self-hosted
    steps:
      - name: start
        run: |
          cd docker
          docker-compose up -d
