name: Deploy Release
on:
  push:
    branches:
      - "develop"
jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

  start-containers:
    runs-on: self-hosted
    steps:
      - name: start
        run: |
          cd docker
          docker-compose -f production.yml up -d
