name: Deploy Release
on:
  push:
    branches:
      - 'automatic-release-tag'
jobs:
  init:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
  check:
    runs-on: self-hosted
    needs:
      - init
    outputs:
      build_frontend: ${{ steps.check.outputs.build_frontend }}
      build_backend: ${{ steps.check.outputs.build_backend }}
    steps:
      - name: Check Frontend
        run: |
          if ! git diff --exit-code HEAD HEAD^ -- frontend
            then echo "::set-output name=build_frontend::true"
            else echo "::set-output name=build_frontend::false"
          fi
      - name: Check Backend
        run: |
          if ! git diff --exit-code HEAD HEAD^ -- backend
            then echo "::set-output name=build_backend::true"
            else echo "::set-output name=build_backend::false"
          fi

  frontend:
    runs-on: self-hosted
    needs:
      - check
    if: needs.check.outputs.build_frontend
    steps:
      - name: Build Frontend
        run: |
          cd frontend
          npm i --unsafe-perm -g npm@latest expo-cli@latest
          npm ci
          npm run build
          cd ../docker
          docker-compose up -d --build frontend

  backend:
    runs-on: self-hosted
    needs:
      - check
    if: needs.check.outputs.build_backend
    steps:
      - name: Build Backend
        run: |
          cd docker
          docker-compose up -d --build backend
