name: Publish Release
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: Create a Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        args: ReleaseComplete
